service: product-service

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  region: eu-west-1
  stage: dev

functions:
  getProducts:
    handler: handler.getProducts    	
    events:
      - http:
          path: products
          method: get
          cors: true
  getProductById:
    handler: handler.getProductById    	
    events:
      - http:
          path: products/{productId}
          method: get
          cors: true
