service: authorization-service

frameworkVersion: '3'
	
useDotenv: true

provider:
  name: aws
  runtime: nodejs16.x
  region: eu-west-1
  stage: dev
  environment:
    REGION: ${env:REGION}
    
plugins:
  - serverless-webpack

functions:
  basicAuthorizer:
    handler: handler.basicAuthorizer
  
# resources:
#   Resources:
#     basicAuthorizer:
#       Type: AWS::Serverless::Function
#       Properties:
#         Handler: handler.basicAuthorizer
#   Outputs:
#     basicAuthorizer:
#       Value: 
#         !GetAtt basicAuthorizer.Arn
#       Export:
#         Name: basicAuthorizer
